http:
  name: HttpServer
  addr: 127.0.0.1:8082
  host: http://127.0.0.1:8082
  picPath: ./static/pic/


tcpPool:
  # 连接类型
  NetWork: tcp
  # tcp服务地址
  Addr: 127.0.0.1:8081
  # 初始化连接数
  InitialCap: 8
  # 最大并发存活连接数
  MaxCap: 20
  # 最大空闲连接
  MaxIdle: 16
  # 连接最大空闲时间，超过该事件则将失效
  IdleTimeout: 15