tcp:
  name: TcpServer
  addr: 127.0.0.1:8081
  host: http://127.0.0.1:8081

mysql:
  Dsn: "root:123qwe@tcp(127.0.0.1:3306)/entry_task?timeout=2s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  ShowLog: true                   # 是否打印SQL日志
  MaxIdleConn: 10                 # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 60                 # 最大打开的连接数
  ConnMaxLifeTime: 4000           # 单个连接最大存活时间
  TableCount: 128                 # 分表数量

redis:
  Addr: 127.0.0.1:6379
  Password: "123456"
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 100
  PoolTimeout: 240
  IsTrace: true
lru:
  Max: 100000